// Autogenerated from Pigeon (v22.6.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is PluginPigeonError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class PluginPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ArithmeticOperation(val raw: Int) {
  ADD(0),
  SUBTRACT(1),
  MULTIPLY(2),
  DIVIDE(3);

  companion object {
    fun ofRaw(raw: Int): ArithmeticOperation? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class PluginPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ArithmeticOperation.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ArithmeticOperation -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ArithmeticHostApi {
  fun performArithmeticOperation(input1: Double, input2: Double, operation: ArithmeticOperation): Double

  companion object {
    /** The codec used by ArithmeticHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PluginPigeonPigeonCodec()
    }
    /** Sets up an instance of `ArithmeticHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ArithmeticHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.plugin_workshop.ArithmeticHostApi.performArithmeticOperation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val input1Arg = args[0] as Double
            val input2Arg = args[1] as Double
            val operationArg = args[2] as ArithmeticOperation
            val wrapped: List<Any?> = try {
              listOf(api.performArithmeticOperation(input1Arg, input2Arg, operationArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
